name: CD - Deploy with Docker Compose

on:
  release:
    types: 
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy with Docker Compose to remote server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: course.prafdin.ru
          port: 2470
          username: yakova
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Navigating to project directory"
            cd ~/multicontainers
            
            echo "Complete rebuild and deploy"
            docker compose down
            docker compose up -d --build
            
            echo "Waiting for services..."
            sleep 30
            
            echo "Checking application"
            curl -f http://localhost:8181/ && echo "Deployment successful" || echo "Health check failed"
            docker compose ps
